services:
  products-api:
    image: products-api:latest
    container_name: products-api
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - products-db
    env_file: .env
    environment:
      - DATABASE_USERNAME
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - APP_ENV
      - SECRET_KEY
    networks:
      - products
      - nginx-proxy

  products-db:
    image: mysql:8.0
    container_name: products-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - products

volumes:
  mysql_data:

networks:
  products:
    name: products-network
    driver: bridge
  nginx-proxy:
    external: true
    name: nginx-proxy-network